'use client';
import {useState,useEffect,type ReactNode} from 'react';import {usePathname} from 'next/navigation';import Link from 'next/link';import FeedbackLink from './feedback-link';
const groups=[
  {name:'日常工作',links:[['/workbench','工作台','◫'],['/alerts','告警与核查','!'],['/tasks','任务与日历','✓'],['/records','农事与照片','▤']]},
  {name:'生产业务',links:[['/inventory','库存与批次','▧'],['/traceability','质量与溯源','⌁'],['/protection','植保作业','◈'],['/agronomy','农情与影像','❋'],['/control-records','控制准备','⊡']]},
  {name:'资源与经营',links:[['/energy','能源记录','⚡'],['/circular','循环物料','↻'],['/machinery','农机服务','⇢'],['/business','费用与补贴','¥'],['/research','科研试验','∴'],['/management','综合指标','▥']]},
  {name:'空间与资料',links:[['/farm-overview','农场空间总览','◉'],['/map','二维地图','⌖'],['/terrain','三维与地形','△'],['/imagery','监控与航次','▣'],['/devices','设备与测点','⊙'],['/objects','对象台账','▦']]},
  {name:'分析与协作',links:[['/analysis','分析复盘','↗'],['/briefings','简报审阅','≡'],['/knowledge','知识资料','▥'],['/assistant','权限内问答','◇'],['/maintenance','维护与复测','＋']]},
  {name:'管理',links:[['/rules','规则审核','§'],['/duty','值班安排','◷'],['/settings','配置管理','⚙'],['/operations','运行与费用','⋯']]},
];
const expert=new Set(['/workbench','/farm-overview','/map','/terrain','/imagery','/analysis','/briefings','/knowledge','/assistant']);
const worker=new Set(['/workbench','/alerts','/tasks','/records','/farm-overview','/map','/imagery','/devices','/objects','/maintenance','/inventory','/protection','/agronomy','/control-records','/energy','/circular','/machinery','/research']);
export default function AppShell({role,children}:{role:string;children:ReactNode}){const path=usePathname(),[open,setOpen]=useState(false),[mobile,setMobile]=useState(false);useEffect(()=>{const media=matchMedia('(max-width:760px)'),change=()=>setMobile(media.matches);change();media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);const links=groups.flatMap(g=>g.links),current=links.find(x=>path===x[0]||path.startsWith(x[0]+'/'))?.[1]??(path==='/account'?'我的账号':'操作帮助');return <div className="app-shell"><a className="skip-link" href="#workspace-content">跳至内容</a><aside className={'app-sidebar'+(open?' is-open':'')} inert={mobile&&!open} aria-hidden={mobile&&!open} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);document.querySelector<HTMLButtonElement>('.nav-toggle')?.focus();}}}><Link className="app-brand" href="/workbench" onClick={()=>setOpen(false)}><span className="brand-mark" aria-hidden="true">禾</span><span>梁子湖<span className="brand-caption">农场工作空间</span></span></Link><nav className="app-navigation" aria-label="平台功能">{groups.map(g=>{const visible=g.links.filter(x=>role==='expert'?expert.has(x[0]):role==='worker'?worker.has(x[0]):(x[0]!=='/operations'||role==='admin')&&(!['/business','/management'].includes(x[0])||['owner','technician','admin'].includes(role)));return visible.length?<section key={g.name}><p>{g.name}</p>{visible.map(([url,label,icon])=><Link href={url} key={url} aria-current={path===url||path.startsWith(url+'/')?'page':undefined} onClick={()=>setOpen(false)}><span aria-hidden="true" className="nav-symbol">{icon}</span>{label}</Link>)}</section>:null;})}</nav><div className="sidebar-foot"><Link href="/help" onClick={()=>setOpen(false)}>操作帮助</Link></div></aside>{open&&<button className="nav-scrim" aria-label="关闭导航" onClick={()=>setOpen(false)}/>}<div className="app-body"><header className="app-topbar"><button className="nav-toggle" aria-label={open?'收起导航':'打开导航'} aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button><div><span className="breadcrumb">农场工作空间 / </span><strong>{current}</strong></div><Link className="account-link" href="/account">我的账号<span aria-hidden="true"> ↗</span></Link></header><main id="workspace-content" className="app-content" tabIndex={-1}>{children}</main><footer className="app-footer"><span>梁子湖 · 每条记录都有依据</span><FeedbackLink/><span>以当前授权和已核实资料为准</span></footer></div></div>;}
