import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
import {withDb} from '../support/db';
import {withApp} from '../support/app';
import {actorFixture,objectFixture,permit} from '../support/fixtures';

test('D3.1 演示隔离、差异化详情、真实新增路径和权限', {timeout:180000},()=>withDb(async pool=>{
 const owner=await actorFixture(pool,'owner'),worker=await actorFixture(pool,'worker'),expert=await actorFixture(pool,'expert'),admin=await actorFixture(pool,'admin');
 const farm=await objectFixture(pool,owner.id);
 await pool.query("UPDATE objects SET name='合成测试农场',code='SYNTH-D31-FARM' WHERE id=$1",[farm]);
 await permit(pool,owner.id,farm,['read','configure']);await permit(pool,worker.id,farm,['read']);
 const tracked=['objects','map_regions','devices','data_sources','alerts','work_orders','device_positions'];
 const counts=async()=>Object.fromEntries(await Promise.all(tracked.map(async table=>[table,Number((await pool.query(`SELECT count(*) AS n FROM ${table}`)).rows[0].n)])));
 await withApp(pool,async app=>{
  const browser=await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{});
  try{
   const context=await browser.newContext({viewport:{width:1440,height:1100},locale:'zh-CN'});
   await context.addCookies([{name:'agri_session',value:await app.authenticate(owner),url:app.origin}]);
   const page=await context.newPage(),writes:string[]=[],errors:string[]=[];
   page.on('request',request=>{if(request.url().includes('/api/v1/')&&!['GET','HEAD'].includes(request.method()))writes.push(`${request.method()} ${request.url()}`);});
   page.on('pageerror',error=>errors.push(error.message));
   const capture=async(name:string)=>{await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(280);await page.screenshot({path:'docs/acceptance/farm-overview-demo/'+name});};
   await mkdir('docs/acceptance/farm-overview-demo',{recursive:true});
   await page.goto(app.origin+'/farm-overview');await page.getByRole('button',{name:/合成测试农场/}).waitFor();
   assert.equal(await page.getByText('演示模式',{exact:true}).count(),0);
   await capture('01-真实空状态.png');
   const before=await counts();
   await page.getByRole('button',{name:/查看演示效果/}).click();
   await page.getByText(/当前所有村庄、地块、设备位置、状态和告警均为合成示例/).waitFor();
   for(const name of ['沙湾示范片区','长岭示范片区','湖东示范片区'])await page.getByRole('button',{name:`定位村庄 ${name}`}).waitFor();
   assert.equal(await page.getByText('3 片区').count(),1);
   await capture('02-演示全场.png');
   await page.getByRole('button',{name:/梁子湖农场（演示总览）/}).click();
   await page.getByRole('complementary',{name:'对象详情'}).getByText('5',{exact:true}).first().waitFor();
   await capture('03-演示农场详情.png');
   await page.getByRole('button',{name:'定位村庄 长岭示范片区'}).click();
   await page.getByRole('complementary',{name:'对象详情'}).getByRole('heading',{name:'长岭示范片区'}).waitFor();
   await capture('04-演示片区详情.png');
   await page.getByRole('button',{name:/长岭养殖塘 B/}).click();
   await page.getByText(/演示溶解氧 4.2 mg\/L/).waitFor();
   await capture('05-演示塘口详情.png');
   await page.getByRole('button',{name:/沙湾 1 号水闸/}).click();
   await page.getByText(/演示开度 65%/).waitFor();
   await capture('06-演示设施详情.png');
   await page.getByRole('button',{name:/植保无人机 U-01/}).first().click();
   await page.getByText(/演示坐标，非真实 GPS/).last().waitFor();
   await capture('07-演示机动设备.png');
   await page.setViewportSize({width:390,height:844});
   await page.goto(app.origin+'/farm-overview');
   await page.getByRole('button',{name:/查看演示效果/}).click();
   await page.getByRole('button',{name:'☰ 对象目录'}).click();
   await page.getByRole('button',{name:/长岭养殖塘 B/}).click();
   await page.getByRole('complementary',{name:'对象详情'}).getByRole('heading',{name:'长岭养殖塘 B'}).waitFor();
   await page.waitForTimeout(350);
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
   await page.getByRole('application',{name:'天地图卫星影像及合成演示对象'}).scrollIntoViewIfNeeded();
   await page.screenshot({path:'docs/acceptance/farm-overview-demo/08-演示手机详情.png'});
   assert.deepEqual(writes,[],'演示模式不得调用正式写接口');assert.deepEqual(await counts(),before,'演示浏览不得改变正式表');
   await page.getByRole('button',{name:'退出演示，返回真实数据'}).click();
   await page.getByRole('button',{name:/合成测试农场/}).waitFor();
   assert.equal(await page.getByText('沙湾示范片区').count(),0);
   assert.equal(await page.evaluate(()=>sessionStorage.getItem('farm-overview-return-v1')),null);
   await page.setViewportSize({width:1440,height:900});
   await page.getByRole('button',{name:'＋ 新增/管理'}).click();
   await page.getByRole('button',{name:'新增村庄'}).click();
   const regionForm=page.getByRole('form',{name:'新增村庄'});
   await regionForm.getByLabel('所属农场').selectOption(farm);
   await regionForm.getByLabel('村庄名称').fill('隔离验收村');
   await regionForm.getByLabel('维护依据').fill('D3.1 隔离测试');
   await regionForm.getByRole('button',{name:'新增村庄'}).click();
   await page.getByRole('button',{name:'定位村庄 隔离验收村'}).waitFor();
   await page.getByRole('link',{name:'新增地块/塘口'}).click();
   const objectForm=page.getByRole('form',{name:'创建对象'});
   await objectForm.getByLabel('所属农场').selectOption(farm);
   await objectForm.getByLabel('类型').selectOption('field');
   await objectForm.getByLabel('唯一编号').fill('SYNTH-D31-FIELD');
   await objectForm.getByLabel('名称').fill('隔离验收地块');
   await objectForm.getByLabel('登记依据').fill('D3.1 隔离测试');
   await objectForm.getByLabel('变更依据').fill('D3.1 新增');
   await Promise.all([page.waitForResponse(response=>response.url().endsWith('/api/v1/objects')&&response.request().method()==='POST'&&response.status()===201),objectForm.getByRole('button',{name:'创建对象'}).click()]);
   await objectForm.getByText('已保存').waitFor();
   const field=(await pool.query("SELECT id,boundary_status,boundary FROM objects WHERE code='SYNTH-D31-FIELD'")).rows[0];
   assert.equal(field.boundary_status,'unknown');assert.equal(field.boundary,null);
   await objectForm.getByLabel('所属农场').selectOption(farm);
   await objectForm.getByLabel('类型').selectOption('pond');
   await objectForm.getByLabel('唯一编号').fill('SYNTH-D31-POND');
   await objectForm.getByLabel('名称').fill('隔离验收塘口');
   await objectForm.getByLabel('登记依据').fill('D3.1 隔离测试');
   await objectForm.getByLabel('变更依据').fill('D3.1 新增');
   await Promise.all([page.waitForResponse(response=>response.url().endsWith('/api/v1/objects')&&response.request().method()==='POST'&&response.status()===201),objectForm.getByRole('button',{name:'创建对象'}).click()]);
   const pond=(await pool.query("SELECT kind,boundary_status FROM objects WHERE code='SYNTH-D31-POND'")).rows[0];
   assert.equal(pond.kind,'pond');assert.equal(pond.boundary_status,'unknown');
   await page.goto(app.origin+'/map#boundary-draft');
   await page.locator('#boundary-draft summary').click();
   const boundaryForm=page.locator('#boundary-draft form');
   await boundaryForm.getByLabel('对象',{exact:true}).selectOption(field.id);
   await boundaryForm.getByLabel('当前对象版本').fill('1');
   await boundaryForm.getByLabel('来源EPSG（4326、4490、3857）').fill('4326');
   await boundaryForm.getByLabel('面边界GeoJSON').fill(JSON.stringify({type:'Polygon',coordinates:[[[114.62,30.24],[114.63,30.24],[114.63,30.25],[114.62,30.25],[114.62,30.24]]]}));
   await boundaryForm.getByLabel('边界状态').selectOption('draft');
   await boundaryForm.getByLabel('来源和确认依据').fill('D3.1 隔离合成边界');
   await boundaryForm.getByRole('button',{name:'保存'}).click();
   await boundaryForm.getByText('已保存').waitFor();
   assert.equal((await pool.query('SELECT boundary_status FROM objects WHERE id=$1',[field.id])).rows[0].boundary_status,'draft');
   assert.equal((await pool.query('SELECT status FROM boundary_versions WHERE object_id=$1',[field.id])).rows[0].status,'draft');
   await page.goto(app.origin+'/objects#new-facility');
   const facilityForm=page.getByRole('form',{name:'创建对象'});
   await facilityForm.getByLabel('所属农场').selectOption(farm);
   await facilityForm.getByLabel('类型').selectOption('facility');
   await facilityForm.getByLabel('唯一编号').fill('SYNTH-D31-GATE');
   await facilityForm.getByLabel('名称').fill('隔离验收水闸');
   await facilityForm.getByLabel('登记依据').fill('D3.1 隔离测试');
   await facilityForm.getByLabel('变更依据').fill('D3.1 新增');
   await facilityForm.getByRole('button',{name:'创建对象'}).click();
   await facilityForm.getByText('已保存').waitFor();
   assert.equal((await pool.query("SELECT kind FROM objects WHERE code='SYNTH-D31-GATE'")).rows[0].kind,'facility');
   await page.goto(app.origin+'/devices#register');
   await page.getByLabel('关联对象').selectOption(farm);
   await page.getByText('先登记数据来源').click();
   const sourceForm=page.getByRole('form',{name:'保存数据来源'});
   await sourceForm.getByLabel('来源编号').fill('SYNTH-D31-SRC');
   await sourceForm.getByLabel('来源名称').fill('隔离测试来源');
   await sourceForm.getByLabel('服务方').fill('隔离测试服务方');
   await sourceForm.getByRole('button',{name:'保存数据来源'}).click();
   await page.getByRole('form',{name:'登记实体设备'}).waitFor();
   const deviceForm=page.getByRole('form',{name:'登记实体设备'});
   await deviceForm.getByLabel('已登记数据来源').selectOption({index:1});
   await deviceForm.getByLabel('厂家或业务编号').fill('SYNTH-U01');
   await deviceForm.getByLabel('设备名称').fill('隔离验收无人机');
   await deviceForm.getByLabel('登记依据').fill('D3.1 隔离测试');
   await deviceForm.getByRole('button',{name:'登记实体设备'}).click();
   await deviceForm.getByText('已保存').waitFor();
   assert.equal((await pool.query("SELECT kind,verified FROM devices WHERE external_id='SYNTH-U01'")).rows[0].verified,false);
   const workerContext=await browser.newContext();try{await workerContext.addCookies([{name:'agri_session',value:await app.authenticate(worker),url:app.origin}]);const workerPage=await workerContext.newPage();await workerPage.goto(app.origin+'/farm-overview');await workerPage.getByRole('button',{name:/合成测试农场/}).waitFor();await workerPage.getByRole('button',{name:'＋ 新增/管理'}).click();assert.equal(await workerPage.getByRole('link',{name:'新增地块/塘口'}).count(),0);const denied=await workerContext.request.post(app.origin+'/api/v1/objects',{headers:{Origin:app.origin},data:{parentId:farm,kind:'field',code:'DENIED',name:'越权',source:'测试'}});assert.equal(denied.status(),403);}finally{await workerContext.close();}
   const adminContext=await browser.newContext();try{await adminContext.addCookies([{name:'agri_session',value:await app.authenticate(admin),url:app.origin}]);const denied=await adminContext.request.post(app.origin+'/api/v1/map-regions',{headers:{Origin:app.origin},data:{farmId:farm,name:'管理员无权新村',source:'测试'}});assert.equal(denied.status(),403,'管理员角色不得替代对象配置授权');await permit(pool,admin.id,farm,['read','configure']);const allowed=await adminContext.request.get(app.origin+'/api/v1/objects?action=configure&limit=200');assert.equal(allowed.status(),200);assert((await allowed.json()).items.some((row:{id:string})=>row.id===farm));}finally{await adminContext.close();}
   const expertContext=await browser.newContext();try{await expertContext.addCookies([{name:'agri_session',value:await app.authenticate(expert),url:app.origin}]);const expertPage=await expertContext.newPage();await expertPage.goto(app.origin+'/farm-overview');await expertPage.getByRole('button',{name:/查看演示效果/}).waitFor();assert.equal(await expertPage.getByText('合成测试农场').count(),0);await expertPage.getByRole('button',{name:/查看演示效果/}).click();await expertPage.getByRole('button',{name:/梁子湖农场（演示总览）/}).waitFor();}finally{await expertContext.close();}
   for(const path of ['/map','/map-prototype','/terrain','/imagery','/objects','/devices','/machinery'])assert.equal((await context.request.get(app.origin+path)).status(),200,path);
   assert.deepEqual(errors,[]);
   await context.close();
  }finally{await browser.close();}
 });
}));
