import {artifactPath} from '../support/artifacts';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {chromium} from 'playwright';
import {withDb} from '../support/db';import {withApp} from '../support/app';import {actorFixture,objectFixture,permit} from '../support/fixtures';import {syntheticAsset} from '../support/agronomy';import {localStore} from '../../src/modules/media/storage';import {transaction} from '../../src/db/pool';import {createLot} from '../../src/modules/inventory/catalog';
test('3C网页真实照片及指数worker、植保部分导入、手机与未下发控制申请',{timeout:180000},()=>withDb(async pool=>{
 const root=await mkdtemp(join(tmpdir(),'phase3-ui-'));try{
 const a=await actorFixture(pool,'technician'),o=await objectFixture(pool,a.id);await permit(pool,a.id,o,['read','record','review','configure','act','share','export']);
 const lot=await transaction(c=>createLot(c,a,{objectId:o,code:randomUUID(),product:'合成植保投入品',kind:'input',unit:'L',basis:'as_is',source:'仅软件测试',requestKey:randomUUID()}),pool),store=localStore(join(root,'source'),join(root,'backup')),rgb=await syntheticAsset(pool,a,o,store,'rgb'),tif=await syntheticAsset(pool,a,o,store,'spectral');
 const source= randomUUID(),device=randomUUID();await pool.query("INSERT INTO data_sources(id,object_id,code,name,provider,created_by) VALUES($1::uuid,$2,$1::text,'合成准备来源','synthetic',$3)",[source,o,a.id]);await pool.query("INSERT INTO devices(id,object_id,source_id,external_id,name,kind,source,created_by) VALUES($1,$2,$3,'demo','合成待验设备','physical','仅测试',$4)",[device,o,source,a.id]);
 await withApp(pool,async app=>{
 const browser=await chromium.launch({executablePath:process.env.AGRI_BROWSER_EXECUTABLE||undefined}),context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 try{await context.addCookies([{name:'agri_session',value:await app.authenticate(a),url:app.origin}]);await page.goto(app.origin+'/agronomy');await page.getByText('分析作物照片',{exact:true}).click();
 const crop=page.locator('form').filter({has:page.getByLabel('照片原件',{exact:true})});await crop.getByLabel('照片原件',{exact:true}).selectOption(rgb.id);await crop.getByRole('button',{name:'保存',exact:true}).click();await crop.getByText('已保存',{exact:true}).waitFor();app.worker('workers/agronomy.ts');await page.getByRole('button',{name:'刷新分析进度',exact:true}).click();await page.getByText(/绿色像素比例100.0%/).waitFor();
 await page.getByText('多光谱反射率产品与分区',{exact:true}).click();const spectral=page.locator('form').filter({has:page.getByLabel('反射率GeoTIFF',{exact:true})});
 await spectral.getByLabel('反射率GeoTIFF',{exact:true}).selectOption(tif.id);await spectral.getByLabel('实际采集时间',{exact:true}).fill('2026-10-03T10:00');await spectral.getByLabel('来源链及未取得文件说明',{exact:true}).fill('合成像素，非真实航片');await spectral.getByLabel('拼接与辐射校正工具、版本',{exact:true}).fill('合成生成器v1');await spectral.getByLabel('指数类型',{exact:true}).selectOption('NDVI');await spectral.getByLabel('已核波段映射',{exact:true}).fill('{"red":0,"nir":1}');await spectral.getByLabel('已核反射率校正',{exact:true}).fill('{"state":"reflectance","scale":1,"offset":0,"evidence":"合成已知像素"}');await spectral.getByLabel('专业选择的指数分界点（最多4个）',{exact:true}).fill('[0,0.6]');await spectral.getByRole('button',{name:'保存',exact:true}).click();await spectral.getByText('已保存',{exact:true}).waitFor();app.worker('workers/agronomy.ts');await page.getByRole('button',{name:'刷新分析进度',exact:true}).click();await page.getByRole('link',{name:'下载带地理参考的指数GeoTIFF'}).waitFor();
 await page.goto(app.origin+'/protection');await page.getByText('登记植保计划',{exact:true}).click();const plan=page.locator('form').filter({has:page.getByLabel('计划名称',{exact:true})});
 for(const [label,value] of [['计划名称','合成网页植保计划'],['作物','水稻'],['作业目标','软件流程验证'],['现场已核生育阶段','未用于现场'],['障碍及位置说明','合成空场'],['敏感邻区核实说明（未知须写明）','仅测试，真实邻区未知'],['执行条件及专业依据','仅工程记录不执行作业'],['计划来源','合成流程']])await plan.getByLabel(label,{exact:true}).fill(value);
 await plan.getByLabel('投入品批次',{exact:true}).selectOption(lot.id);await plan.getByLabel('已核地块边界GeoJSON',{exact:true}).fill(JSON.stringify({type:'Polygon',coordinates:[[[114,30],[114.001,30],[114.001,30.001],[114,30.001],[114,30]]]}));await plan.getByRole('button',{name:'保存',exact:true}).click();await plan.getByText('已保存',{exact:true}).waitFor();
 const p=(await pool.query('SELECT id FROM protection_plans')).rows[0];await page.getByText('离线批量导入作业',{exact:true}).click();const at=new Date().toISOString(),row={externalId:'offline1',planId:p.id,operator:'合成操作者',startedAt:at,endedAt:at,track:[],unit:'L',materialQuantity:null,evidence:'仅测试'};
 await page.getByLabel('选择离线JSON文件',{exact:true}).setInputFiles({name:'合成离线作业.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([row,{...row,externalId:'offline2',unit:'kg'}]))});
 const imported=page.locator('form').filter({has:page.getByLabel('稳定来源或设备编号',{exact:true})});await imported.getByLabel('稳定来源或设备编号',{exact:true}).fill('仅合成导入');await imported.getByRole('button',{name:'保存',exact:true}).click();await imported.getByText(/已导入1行；1行未导入/).waitFor();
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('.app-sidebar')!.getBoundingClientRect().right<=1);await page.evaluate(()=>scrollTo(0,0));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:artifactPath('验收/3c/植保手机合成实测.png'),fullPage:true});
 await page.goto(app.origin+'/control-records');await page.getByText('登记控制申请（不会下发）',{exact:true}).click();const control=page.locator('form').filter({has:page.getByLabel('本次申请目的',{exact:true})});
 await page.getByLabel('当前设备',{exact:true}).selectOption(device);await control.getByLabel('本次申请目的',{exact:true}).fill('验证默认拦截');await control.getByLabel('本次授权依据',{exact:true}).fill('仅工程测试');await control.getByLabel('本次现场条件',{exact:true}).fill('合成记录');await control.getByRole('button',{name:'保存',exact:true}).click();await control.getByText('已保存',{exact:true}).waitFor();await page.getByText(/申请已登记，未下发。/).waitFor();
 assert.equal((await pool.query('SELECT dispatched FROM control_requests')).rows[0].dispatched,false);
 for(const endpoint of ['inventory','traceability','protection','agronomy','control-records'])assert.equal((await context.request.post(app.origin+'/api/v1/'+endpoint+'/constructor',{headers:{Origin:app.origin},data:{}})).status(),404);
 assert.deepEqual(errors,[]);
 }catch(e){await page.screenshot({path:'.local/3c-页面失败.png',fullPage:true});console.log(await page.locator('.form-error').allTextContents());throw e;}finally{await browser.close();}
 },{mediaRoot:root});
 }finally{await rm(root,{recursive:true,force:true});}
}));
