import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { database, transaction } from '../../src/db/pool';
import { createDraftPoint, deleteDraftPoint, listDraftPoints, updateDraftPoint } from '../../src/modules/map-prototype/draft-points';
import { actorFixture } from '../support/fixtures';
import { withDb } from '../support/db';

test('个人卫星点位：中文、坐标、私有隔离、重复保存、版本及审计', () => withDb(async pool => {
  const owner = await actorFixture(pool);
  const other = await actorFixture(pool);
  const expert = await actorFixture(pool, 'expert');
  const requestKey = randomUUID();
  const body = { requestKey, name: '一号水泵', note: '  首次记录  ', lng: 114.635, lat: 30.25 };
  const first = await transaction(client => createDraftPoint(client, owner, body), pool);
  assert.equal(first.name, '一号水泵');
  assert.equal(first.note, '首次记录');
  assert.equal(first.lng, body.lng);
  assert.equal(first.lat, body.lat);
  assert.equal(first.version, 1);
  const repeat = await transaction(client => createDraftPoint(client, owner, body), pool);
  assert.equal(repeat.id, first.id);
  assert.equal((await pool.query('SELECT count(*) FROM satellite_draft_points')).rows[0].count, '1');
  await assert.rejects(() => transaction(client => createDraftPoint(client, owner, { ...body, name: '长岭3号监测点' }), pool), { code: 'REQUEST_KEY_REUSED' });
  assert.equal((await database(client => listDraftPoints(client, owner), pool)).points.length, 1);
  assert.equal((await database(client => listDraftPoints(client, other), pool)).points.length, 0);
  await assert.rejects(() => database(client => listDraftPoints(client, expert), pool), { status: 403 });
  await assert.rejects(() => transaction(client => updateDraftPoint(client, other, first.id, { version: 1, name: '他人修改' }), pool), { status: 404 });
  await assert.rejects(() => transaction(client => deleteDraftPoint(client, other, first.id, { version: 1 }), pool), { status: 404 });
  await assert.rejects(() => transaction(client => createDraftPoint(client, owner, { ...body, requestKey: randomUUID(), lng: 181 }), pool), { code: 'INVALID_COORDINATES' });
  await assert.rejects(() => transaction(client => createDraftPoint(client, owner, { ...body, requestKey: randomUUID(), lat: -91 }), pool), { code: 'INVALID_COORDINATES' });
  await assert.rejects(() => transaction(client => createDraftPoint(client, owner, { ...body, requestKey: randomUUID(), name: '' }), pool), { status: 400 });
  const updated = await transaction(client => updateDraftPoint(client, owner, first.id, { version: 1, name: '长岭3号监测点', note: '二次核对' }), pool);
  assert.equal(updated.name, '长岭3号监测点');
  assert.equal(updated.version, 2);
  assert.equal(updated.lng, body.lng);
  assert.equal(updated.lat, body.lat);
  await assert.rejects(() => transaction(client => updateDraftPoint(client, owner, first.id, { version: 1, name: '旧版本' }), pool), { code: 'POINT_VERSION_CHANGED' });
  assert.equal((await database(client => listDraftPoints(client, owner), pool)).points[0].name, '长岭3号监测点');
  await transaction(client => deleteDraftPoint(client, owner, first.id, { version: 2 }), pool);
  assert.equal((await database(client => listDraftPoints(client, owner), pool)).points.length, 0);
  const audit = await pool.query("SELECT event_type FROM audit_events WHERE actor_id=$1 AND event_type LIKE 'satellite_draft_point_%' ORDER BY occurred_at", [owner.id]);
  assert.deepEqual(audit.rows.map(row => row.event_type).sort(), ['satellite_draft_point_created', 'satellite_draft_point_deleted', 'satellite_draft_point_updated']);
}));
