'use client';
import {useRef,useState} from 'react';
import MapShares from './shares';
import {useApi} from '@/components/platform/use-api';import ActionForm from '@/components/platform/action-form';import {Field,Pick} from '@/components/platform/fields';
type Geometry={type:string;coordinates:number[][][]|number[][][][]|number[]};
type MapObject={id:string;name:string;code:string;version:number;boundary_version_id?:string;boundary_status:string;geometry:Geometry|null};
type Raster={id:string;file_id:string;flight_id:string;object_id:string;bounds:number[];source_ref:string;state:string;error_code:string|null;preview_asset_id:string|null};
type Flight={id:string;object_id:string;started_at:string;finished_at:string;capture_conditions:unknown;source_ref:string};
type Data={items:MapObject[];devices:{id:string;name:string;object_id:string;position_id?:string;verified:boolean;geometry:Geometry|null}[];coverages:{id:string;flight_id:string;object_id:string;version:number;status:string;source_ref:string;geometry:Geometry}[];rasters:Raster[];flights:Flight[];annotations:{id:string;object_id:string;note:string;source_ref:string|null;location:{type:string;lng:number;lat:number}|null}[];limitations:string[]};
const rings=(g:Geometry):number[][][]=>g.type==='Polygon'?g.coordinates as number[][][]:g.type==='MultiPolygon'?(g.coordinates as number[][][][]).flat():[];
export default function MapPanel(){
 const map=useApi<Data>('/api/v1/map'),me=useApi<{actor:{role:string};scopes:{action:string;objectIds:string[]}[]}>('/api/v1/me'),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[layers,setLayers]=useState({objects:true,devices:true,coverages:true,rasters:true,annotations:true}),[selected,setSelected]=useState<MapObject|null>(null),[compare,setCompare]=useState(['','']),[search,setSearch]=useState('');const moved=useRef(false);const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);
 if(map.error)return <p className="form-error">{map.error}</p>;if(!map.data)return <p>正在读取地图…</p>;const data=map.data,all:number[][]=[];for(const o of [...data.items,...data.coverages])if(o.geometry)for(const ring of rings(o.geometry))all.push(...ring);for(const d of data.devices)if(d.geometry)all.push(d.geometry.coordinates as number[]);for(const r of data.rasters)all.push([r.bounds[0],r.bounds[1]],[r.bounds[2],r.bounds[3]]);for(const a of data.annotations)if(a.location?.type==='geographic')all.push([a.location.lng,a.location.lat]);
 const xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),dx=Math.max(.0001,maxX-minX),dy=Math.max(.0001,maxY-minY),project=(p:number[])=>[(p[0]-minX)/dx*850+25,450-(p[1]-minY)/dy*400],path=(g:Geometry)=>rings(g).map(r=>'M'+r.map(p=>project(p).join(',')).join(' L')+' Z').join(' '),configure=me.data?.scopes.some(s=>s.action==='configure'&&s.objectIds.length),record=me.data?.scopes.some(s=>s.action==='record'&&s.objectIds.length),review=me.data?.scopes.some(s=>s.action==='review'&&s.objectIds.length),expert=me.data?.actor.role==='expert';
 const focusObject=(o:MapObject)=>{setSelected(o);if(!o.geometry)return;const points=rings(o.geometry).flat().map(project),xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);setPan({x:(Math.min(...xs)+Math.max(...xs))/2-450,y:(Math.min(...ys)+Math.max(...ys))/2-250});setZoom(Math.min(8,Math.max(1,.8*Math.min(900/Math.max(1,Math.max(...xs)-Math.min(...xs)),500/Math.max(1,Math.max(...ys)-Math.min(...ys))))));};
 return <><div className="map-heading"><label>查找地图对象<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="输入对象名称或编号"/></label><a className="secondary-link" href="/terrain">三维与地形资料 →</a></div><p className="hint">WGS84二维资料。边界、点位、航次覆盖、已配准预览和疑点分层；虚线为草稿。地图邻近不证明归属或水力连通，未确认采集条件时不作变化结论。</p><div className="filter-grid">{Object.entries(layers).map(([name,on])=><label key={name}><input type="checkbox" checked={on} onChange={e=>setLayers({...layers,[name]:e.target.checked})}/>{({objects:'对象边界',devices:'设备点位',coverages:'航次覆盖',rasters:'正射预览',annotations:'定位疑点'})[name as keyof typeof layers]}</label>)}<label>缩放<input type="range" min="1" max="8" step=".1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><button type="button" aria-label="放大地图" onClick={()=>setZoom(z=>Math.min(8,z+.5))}>＋ 放大</button><button type="button" aria-label="缩小地图" onClick={()=>setZoom(z=>Math.max(1,z-.5))}>− 缩小</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0});}}>复位视图</button></div>
 {all.length?<div className="map-window"><svg className="farm-map" style={{touchAction:'none'}} viewBox={`${450-450/zoom+pan.x} ${250-250/zoom+pan.y} ${900/zoom} ${500/zoom}`} role="img" tabIndex={0} aria-label="对象、航次、影像与疑点地图" onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','0'].includes(e.key)){e.preventDefault();if(e.key==='+')setZoom(z=>Math.min(8,z+.5));else if(e.key==='-')setZoom(z=>Math.max(1,z-.5));else if(e.key==='0'){setZoom(1);setPan({x:0,y:0});}else setPan(p=>({x:p.x+(e.key==='ArrowRight'?40:e.key==='ArrowLeft'?-40:0)/zoom,y:p.y+(e.key==='ArrowDown'?40:e.key==='ArrowUp'?-40:0)/zoom}));}}} onClickCapture={e=>{if(moved.current){e.preventDefault();e.stopPropagation();}}} onPointerDown={e=>{moved.current=false;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};}} onPointerMove={e=>{if(!drag.current)return;if(Math.abs(e.clientX-drag.current.x)+Math.abs(e.clientY-drag.current.y)>5)moved.current=true;const b=e.currentTarget.getBoundingClientRect();setPan({x:drag.current.px-(e.clientX-drag.current.x)/b.width*900/zoom,y:drag.current.py-(e.clientY-drag.current.y)/b.height*500/zoom});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><rect x="-100000" y="-100000" width="200000" height="200000" fill="#edf3e5"/>
 {layers.objects&&data.items.map(o=>o.geometry&&<a key={o.boundary_version_id??o.id} href={expert?'#selected-map-detail':'/objects/'+o.id} onClick={()=>setSelected(o)}><path d={path(o.geometry)} fill={o.boundary_status==='verified'?'#b9d4ad':'#d9dbcd'} fillRule="evenodd" stroke="#28543d" strokeWidth={selected?.id===o.id?4:2} strokeDasharray={o.boundary_status==='verified'?undefined:'6 4'}><title>{o.name} · 边界版本{o.version}</title></path></a>)}
 {layers.rasters&&data.rasters.filter(r=>r.state==='complete'&&r.preview_asset_id).map(r=>{const p=project([r.bounds[0],r.bounds[3]]),q=project([r.bounds[2],r.bounds[1]]);return <image key={r.id} href={'/api/v1/media/'+r.preview_asset_id} x={p[0]} y={p[1]} width={q[0]-p[0]} height={q[1]-p[1]} preserveAspectRatio="none" opacity=".7" pointerEvents="none"><title>{r.source_ref}；附件须有当前权限</title></image>;})}
 {layers.coverages&&data.coverages.map(c=><path key={c.id} d={path(c.geometry)} fill="none" stroke="#3173a6" strokeWidth="2" strokeDasharray={c.status==='verified'?undefined:'6 4'}><title>航次覆盖v{c.version}：{c.source_ref}</title></path>)}
 {layers.devices&&data.devices.map(d=>d.geometry&&<circle key={d.id} cx={project(d.geometry.coordinates as number[])[0]} cy={project(d.geometry.coordinates as number[])[1]} r="5" fill={d.verified?'#28543d':'#c28d37'}><title>{d.name}</title></circle>)}
 {layers.annotations&&data.annotations.filter(a=>a.location?.type==='geographic').map(a=><circle key={a.id} cx={project([a.location!.lng,a.location!.lat])[0]} cy={project([a.location!.lng,a.location!.lat])[1]} r="6" fill="#b34438"><title>{a.note}；{a.source_ref}</title></circle>)}
 </svg></div>:<p className="empty-state">尚无已登记空间资料，未生成虚构地图。</p>}
 {selected&&<section id="selected-map-detail" className="rule-card"><h2>{selected.name}</h2><p>{selected.code}；边界版本{selected.version}；{selected.boundary_status==='verified'?'已确认':'草稿'}；分享ID {selected.boundary_version_id}</p>{!expert&&<a href={'/objects/'+selected.id}>查看对象农事与监测详情</a>}</section>}
 <p className="hint">对象{data.items.length}个 · 设备{data.devices.length}个 · 覆盖{data.coverages.length}份 · 预览{data.rasters.length}份。地图可用方向键平移，＋/−缩放，0复位。</p><ul className="map-object-list">{data.items.filter(o=>(o.name+o.code).includes(search)).map(o=><li key={o.boundary_version_id??o.id}><button onClick={()=>focusObject(o)}>{o.name} · {o.code}</button>；版本{o.version}；{o.geometry?'边界已登记':'缺坐标'}</li>)}</ul><ul>{data.rasters.filter(r=>r.state!=='complete').map(r=><li key={r.id}>正射预览{r.state==='queued'?'待生成':'未完成'}：{r.error_code??r.source_ref}</li>)}</ul>
 <h2>两个时期的成果并列</h2><p className="hint">只比较同对象已确认可视成果，采集条件、加工依据和缺口一起保留；不自动给出农业变化结论。</p><div className="status-grid">{[0,1].map(i=><section key={i}><label>{i?'后一个时期':'前一个时期'}<select value={compare[i]} onChange={e=>setCompare(compare.map((v,j)=>i===j?e.target.value:v))}><option value="">选择成果预览</option>{data.rasters.filter(r=>r.state==='complete').map(r=><option value={r.id} key={r.id}>{r.source_ref}</option>)}</select></label>{(()=>{const r=data.rasters.find(r=>r.id===compare[i]);if(!r)return null;const f=data.flights.find(f=>f.id===r.flight_id);return <><img src={'/api/v1/media/'+r.preview_asset_id} alt={r.source_ref} style={{maxWidth:'100%'}}/><p>{f?new Date(f.started_at).toLocaleString():'航次时段尚未分享'}</p><p>加工/配准：{r.source_ref}</p>{f&&<p>采集条件：{JSON.stringify(f.capture_conditions)}</p>}</>;})()}</section>)}</div>{compare.every(Boolean)&&data.rasters.find(r=>r.id===compare[0])?.object_id!==data.rasters.find(r=>r.id===compare[1])?.object_id&&<p className="form-error">选择了不同对象，只能分别查看，不能作为跨期对比。</p>}
 {configure&&<><details id="boundary-draft"><summary>登记边界版本</summary><ActionForm path="/api/v1/map" numbers={['version','sourceCrs']} jsonFields={['geometry']} onSaved={()=>void map.reload()}><Pick name="objectId" label="对象" options={data.items}/><Field name="version" label="当前对象版本" type="number"/><Field name="sourceCrs" label="来源EPSG（4326、4490、3857）" type="number"/><label>面边界GeoJSON<textarea name="geometry" required rows={5}/></label><Pick name="status" label="边界状态" options={[{id:'draft',name:'草稿'},{id:'verified',name:'经专业确认'}]}/><Field name="source" label="来源和确认依据"/></ActionForm></details><details><summary>登记设备点位版本</summary><ActionForm path="/api/v1/map" numbers={['lng','lat']} booleans={['verified']} onSaved={()=>void map.reload()}><input name="operation" type="hidden" value="position"/><Pick name="deviceId" label="设备" options={data.devices}/><Field name="lng" label="WGS84经度" type="number"/><Field name="lat" label="WGS84纬度" type="number"/><Field name="source" label="定位依据"/><label><input name="verified" type="checkbox"/>已核实现场位置</label></ActionForm></details></>}
 {record&&<details><summary>登记航次覆盖版本</summary><ActionForm path="/api/v1/map" stableKey numbers={['sourceCrs']} jsonFields={['geometry']} onSaved={()=>void map.reload()}><input name="operation" type="hidden" value="coverage"/><Pick name="flightId" label="航次" options={data.flights.map(f=>({id:f.id,name:new Date(f.started_at).toLocaleString()}))}/><Field name="sourceCrs" label="来源EPSG（4326、4490、3857）" type="number"/><label>覆盖GeoJSON<textarea name="geometry" required rows={4}/></label><Pick name="status" label="覆盖状态" options={[{id:'draft',name:'草稿'},{id:'verified',name:'经审核确认'}]}/><Field name="sourceRef" label="覆盖来源/处理依据"/></ActionForm></details>}
 {record&&review&&<details><summary>生成私有二维正射预览</summary><ActionForm path="/api/v1/map" stableKey numbers={['sourceCrs']} jsonFields={['bounds']} booleans={['confirm']} onSaved={()=>void map.reload()}><input name="operation" type="hidden" value="raster"/><Field name="fileId" label="已完整入库的正射文件ID"/><input name="sourceCrs" type="hidden" value="4326"/><label>WGS84矩形范围[xmin,ymin,xmax,ymax]<textarea name="bounds" required/></label><Field name="sourceRef" label="正射校正及配准依据"/><label><input name="confirm" type="checkbox" required/>已核实为北向WGS84正射；未校正原片只并列，不猜覆盖</label></ActionForm></details>}
 {me.data?.scopes.some(s=>s.action==='share'&&s.objectIds.length)&&<MapShares resources={[...data.items.filter(o=>o.boundary_version_id).map(o=>({id:o.boundary_version_id!,type:'map',objectId:o.id,label:o.name+'边界v'+o.version})),...data.devices.filter(d=>d.position_id).map(d=>({id:d.position_id!,type:'position',objectId:d.object_id,label:d.name+'点位'})),...data.coverages.map(c=>({id:c.id,type:'coverage',objectId:c.object_id,label:'航次覆盖v'+c.version+' '+c.source_ref})),...data.flights.map(f=>({id:f.id,type:'flight',objectId:f.object_id,label:'航次 '+new Date(f.started_at).toLocaleString()})),...data.rasters.map(r=>({id:r.id,type:'raster',objectId:r.object_id,label:'配准信息 '+r.source_ref})),...data.rasters.filter(r=>r.preview_asset_id).map(r=>({id:r.preview_asset_id!,type:'media',objectId:r.object_id,label:'预览附件 '+r.source_ref})),...data.annotations.map(a=>({id:a.id,type:'annotation',objectId:a.object_id,label:'疑点 '+a.note}))]}/>}
 </>;
}
