import type {PoolClient} from 'pg';import type {Actor} from '../../platform/types';import {AppError} from '../../platform/error';import {text,time} from '../../platform/validation';import {uuid} from '../identity/common';import {scope} from './common';
const resources={research_protocol:'research_protocols',research_result:'research_results',management_report:'management_reports',stock_lot:'stock_lots',protection_plan:'protection_plans',prescription_map:'prescription_maps',protection_execution:'protection_executions',crop_analysis:'crop_analyses',spectral_product:'spectral_products',agronomy_notice:'agronomy_notices',record:'farm_records',media:'media_assets',metric:'metric_results',definition:'metric_definitions',weather:'weather_records',flight:'flights',calendar:'calendar_versions',camera_event:'camera_events',image_review:'image_reviews',task:'field_tasks',briefing_item:'briefing_items',alert:'alerts',knowledge:'knowledge_documents',map:'boundary_versions',position:'device_positions',coverage:'flight_coverages',raster:'flight_rasters',annotation:'flight_annotations',image_sample:'image_field_samples',comparison_definition:'comparison_definitions',comparison:'comparison_results',camera:'devices',terrain_scene:'terrain_scenes',hydraulic_link:'hydraulic_links',elevation:'device_elevations'} as const;
export async function shareResource(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.objectId);await scope(c,a,b.objectId,'share');await scope(c,a,b.objectId,'read');uuid(b.recipientId);const user=(await c.query('SELECT role,enabled FROM users WHERE id=$1',[b.recipientId])).rows[0];if(!user?.enabled||user.role!=='expert')throw new AppError(422,'EXPERT_RECIPIENT','此入口只创建明确专家事项授权');await import('../identity/access').then(m=>m.assertAccess(c,{id:b.recipientId as string,role:'expert',enabled:true,mfaVerified:true},{objectId:b.objectId as string,action:'read',at:new Date().toISOString()}));
 uuid(b.resourceId);const type=text(b.resourceType,'资料类型',40) as keyof typeof resources;if(!Object.hasOwn(resources,type))throw new AppError(400,'RESOURCE_TYPE','资料类型未定义');const r=(await c.query('SELECT * FROM '+resources[type]+' WHERE id=$1',[b.resourceId])).rows[0];if(r&&type==='annotation')r.object_id=(await c.query('SELECT object_id FROM flights WHERE id=$1',[r.flight_id])).rows[0]?.object_id;if(!r||(type==='knowledge'?!r.object_ids.includes(b.objectId):r.object_id!==b.objectId))throw new AppError(422,'RESOURCE_SCOPE','资料不属于所选对象');const expires=time(b.expiresAt);if(Date.parse(expires)<=Date.now()||Date.parse(expires)-Date.now()>31*86400000)throw new AppError(400,'SHARE_EXPIRY','授权期限须在未来31天内');const from=b.from?time(b.from):null,to=b.to?time(b.to):null;if((from===null)!==(to===null)||(from&&to&&from>=to))throw new AppError(400,'SHARE_PERIOD','资料时段须成对且先后有效');if(from&&to&&type!=='camera'){const start=r.window_start??r.occurred_at??r.captured_at??r.started_at??r.opened_at??r.measured_at??(['map','position','coverage','raster','annotation','hydraulic_link','elevation'].includes(type)?r.created_at:null),end=r.window_end??r.finished_at??start;if(!start||!end)throw new AppError(422,'RESOURCE_TIME_UNKNOWN','资料时间未知，不能宣称落入限定时段');if(new Date(start)<new Date(from)||(r.window_end||r.finished_at?new Date(end)>new Date(to):new Date(end)>=new Date(to)))throw new AppError(422,'RESOURCE_TIME_SCOPE','所选资料不完整落在授权时段内');}return(await c.query('INSERT INTO resource_grants(user_id,object_id,resource_type,resource_id,from_at,to_at,expires_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,resource_type,resource_id,expires_at',[b.recipientId,b.objectId,type,b.resourceId,from,to,expires,a.id])).rows[0];}
export async function revokeResource(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.id);const g=(await c.query('SELECT * FROM resource_grants WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!g)throw new AppError(404,'SHARE_NOT_FOUND','事项授权不存在');await scope(c,a,g.object_id,'share');await c.query('UPDATE resource_grants SET revoked_at=COALESCE(revoked_at,now()) WHERE id=$1',[g.id]);return {id:g.id,revoked:true};}
export async function enforceExpertApi(c:PoolClient,a:Actor,request:Request){if(a.role!=='expert')return;const path=new URL(request.url).pathname;
 if(/^\/api\/v1\/(map|farm-overview|records|calendars|tasks|cameras|flights|analysis|weather|knowledge|assistant|briefings|image-review|workbench|references|terrain|inventory|traceability|protection|agronomy|research|management)(\/|$)/.test(path))return;
 const alert=/^\/api\/v1\/alerts\/([a-f0-9-]{36})(?:\/|$)/.exec(path);if(alert){const r=(await c.query('SELECT object_id FROM alerts WHERE id=$1',[alert[1]])).rows[0];if(r){await scope(c,a,r.object_id,'read','alert',alert[1]);return;}}
 throw new AppError(403,'EXPERT_ITEM_ONLY','专家请从明确分享的事项、指标或资料入口访问，不能浏览全场历史');
}
